title: "42 Rome Student Docs"
description: "Open source documentation for 42 Rome students"
baseurl: ""
url: "https://42bderoma.github.io/42romeStudentDocs"

# Theme settings
remote_theme: pages-themes/leap-day@v0.2.0

# Optional theme configuration
show_downloads: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
